"""add address_verification_status to birthday_orders

Revision ID: cb458018416c
Revises: dcde696849a5
Create Date: 2026-08-14 17:43:36.612248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb458018416c'
down_revision: Union[str, Sequence[str], None] = 'dcde696849a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand so existing rows backfill to NOT_CHECKED
    # instead of failing the NOT NULL constraint; dropped after backfill so
    # the ORM-level Python default (not a DB default) governs new rows,
    # matching every other column on this model.
    with op.batch_alter_table('birthday_orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'address_verification_status', sa.String(length=32),
                nullable=False, server_default='NOT_CHECKED',
            )
        )
    with op.batch_alter_table('birthday_orders', schema=None) as batch_op:
        batch_op.alter_column('address_verification_status', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthday_orders', schema=None) as batch_op:
        batch_op.drop_column('address_verification_status')

    # ### end Alembic commands ###
