"""birthday-api initial schema

Phase A domain model: birthday.db owns everything DijiBirthday-specific —
birthday orders, suppliers (locations/catalogue/users), order events,
special requirements, supplier communications, detection config, and the
per-year order-reference sequence. No table here has a foreign key to
`users` (Platform Core's own database owns User) — `created_by`/
`actor_id`/`updated_by` are opaque ids, mirroring talent-api's initial
schema. See docs/platform/service-architecture.md "Data ownership across
services".

Revision ID: dcde696849a5
Revises:
Create Date: 2026-08-14 01:59:16.528238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcde696849a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday_detection_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normal_threshold_days', sa.Integer(), nullable=False),
    sa.Column('short_notice_threshold_days', sa.Integer(), nullable=False),
    sa.Column('urgent_threshold_days', sa.Integer(), nullable=False),
    sa.Column('window_lookback_days', sa.Integer(), nullable=False),
    sa.Column('window_lookahead_days', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_sequences_year'), ['year'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=False),
    sa.Column('primary_contact_phone', sa.String(length=64), nullable=False),
    sa.Column('escalation_contact_name', sa.String(length=255), nullable=False),
    sa.Column('escalation_contact_email', sa.String(length=255), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.String(length=255), nullable=False),
    sa.Column('cutoff_time', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthday_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_reference', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('employee_email', sa.String(length=255), nullable=False),
    sa.Column('birthday_date', sa.Date(), nullable=False),
    sa.Column('birthday_year', sa.Integer(), nullable=False),
    sa.Column('office_location', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('lead_time_class', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hold_reason', sa.String(length=500), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('requires_admin_review', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('has_delivery_issue', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'birthday_year', name='uq_birthday_orders_employee_year')
    )
    with op.batch_alter_table('birthday_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birthday_orders_birthday_year'), ['birthday_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_birthday_orders_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_birthday_orders_order_reference'), ['order_reference'], unique=True)

    op.create_table('supplier_catalogue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_catalogue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_catalogue_items_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('office_location', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_locations_office_location'), ['office_location'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_locations_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('supplier_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_users_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['birthday_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('special_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['birthday_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('special_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_special_requirements_order_id'), ['order_id'], unique=False)

    op.create_table('supplier_communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['birthday_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_communications_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_communications_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_communications_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_communications_order_id'))

    op.drop_table('supplier_communications')
    with op.batch_alter_table('special_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_special_requirements_order_id'))

    op.drop_table('special_requirements')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('supplier_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_users_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_users_email'))

    op.drop_table('supplier_users')
    with op.batch_alter_table('supplier_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_locations_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_locations_office_location'))

    op.drop_table('supplier_locations')
    with op.batch_alter_table('supplier_catalogue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_catalogue_items_supplier_id'))

    op.drop_table('supplier_catalogue_items')
    with op.batch_alter_table('birthday_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birthday_orders_order_reference'))
        batch_op.drop_index(batch_op.f('ix_birthday_orders_employee_id'))
        batch_op.drop_index(batch_op.f('ix_birthday_orders_birthday_year'))

    op.drop_table('birthday_orders')
    op.drop_table('suppliers')
    with op.batch_alter_table('order_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_sequences_year'))

    op.drop_table('order_sequences')
    op.drop_table('birthday_detection_configs')
    # ### end Alembic commands ###
